on:
  workflow_dispatch:
jobs:
  zip:
    name: Package plugin file
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: list files
        run: |
          ls
      - name: create zip
        run: |
          zip plugin.zip ./ -r
      - name: list files
        run: |
          ls
    
